name: CI_BUILD_SAST

on:
  pull_request:
    branches: [develop]

jobs:
  build_and_sca:
    name: 'Build and SAST'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Config GitHub
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]
            
      - name: run pnpm audit
        run: pnpm audit

      - name: install pnpm
        run: pnpm install --frozen-lockfile

      # SONAR CLOUD
      - name: SonarCloud
        if: always()
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: SonarCloud Scan
        if: always()
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}