name: SCA Tests

on:
  pull_request:
    branches: [develop]

jobs:
  sca_depcheck:
    name: 'Owasp Dependency Check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Config GitHub
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"
      
      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: install pnpm
        run: pnpm install --frozen-lockfile

      # SCA
      
      # OWASP DEPENDENCY CHECK
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'tcc-password-manager'
          path: './'
          format: 'HTML'
          out: '.'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Check
        run: ls

      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
          name: Depcheck report
          path:  ${{github.workspace}}

      - name: Save Deṕcheck Report on Branch
        if: always()
        run: |
          git clone "https://x-access-token:${{secrets.TOKEN_GIT}}@github.com/tcc-lucas-dafne/${{secrets.NAME_REPO_GIT}}" ${{secrets.NAME_REPO_GIT}}
          cd ${{secrets.NAME_REPO_GIT}}

          echo "GITHUB_REF: ${GITHUB_REF}"

          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          elif [[ "${GITHUB_REF}" == refs/pull/*/merge ]]; then
            BRANCH_NAME="refs/pull/${GITHUB_REF#refs/pull/}"
          else
            echo "Unsupported GITHUB_REF: ${GITHUB_REF}"
            exit 1
          fi

          echo "BRANCH_NAME: ${BRANCH_NAME}"

          git fetch
          git checkout ${BRANCH_NAME}
          
          current_date=$(date +%Y-%m-%d)
          rm -rf reports/owasp_dependency_check/${current_date} && mkdir -p reports/owasp_dependency_check/${current_date}
          cp -R ${{github.workspace}}/dependency-check-report.html reports/owasp_dependency_check/${current_date}
          git add .
          git commit -m "Adicionando relatório no repositório ${{ github.event.repository.name }} ${{ github.ref_name }} [skip ci]"
          git push origin ${BRANCH_NAME}
      
      - name: Save Depcheck Report on Develop
        if: always()
        run: |
          if [ ! -d "${{secrets.NAME_REPO_GIT}}" ]; then
            git clone "https://x-access-token:${{secrets.TOKEN_GIT}}@github.com/tcc-lucas-dafne/${{secrets.NAME_REPO_GIT}}" ${{secrets.NAME_REPO_GIT}}
          fi
          cd ${{secrets.NAME_REPO_GIT}}

          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$current_branch" != "develop" ]; then
            git checkout develop
          fi

          current_date=$(date +%Y-%m-%d)
          rm -rf reports/owasp_dependency_check/${current_date} && mkdir -p reports/owasp_dependency_check/${current_date}
          cp -R ${{github.workspace}}/dependency-check-report.html reports/owasp_dependency_check/${current_date}
          git add .
          git commit -m "Adicionando relatório no repositório ${{ github.event.repository.name }} ${{ github.ref_name }} [skip ci]"
          git push origin develop
      