name: SCA Tests

on:
  pull_request:
    branches: [develop]
  push:
    branches: [results]

jobs:
  sca_depcheck:
    name: 'SCA'
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Config GitHub
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"
      
      # - uses: pnpm/action-setup@v4
      #   with:
      #     version: 8

      # - name: install pnpm
      #   run: pnpm install --frozen-lockfile

      - name: install npm
        run: npm install --frozen-lockfile

      - name: files
        run: ls

      # SCA
      # SNYK
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      # - name: Upload result to GitHub Code Scanning
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: snyk.sarif
      #     category: my-analysis-tool
      
      - name: install npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GIT }}
        run: npm ci

      # SCA
      # SNYK
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          category: my-analysis-tool
      
      # OWASP DEPENDENCY CHECK
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'tcc-password-manager'
          path: './'
          format: 'ALL'
          out: 'depcheck'
          args: >
            --enableRetired
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: depcheck/dependency-check-report.sarif

      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
           name: Depcheck report
           path:  ${{github.workspace}}/depcheck

      # - name: PR comment with file
      #   uses: thollander/actions-comment-pull-request@v2
      #   env:
      #     PR_NUMBER: ${{ github.event.number }}
      #   with:
      #     message: |
      #       Hello World!
      #     filePath: Depcheck report.zip
      #     pr_number: $PR_NUMBER
