name: Depcheck

on:
  pull_request:
    branches: [develop]

jobs:
  config:
    name: 'config'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Config GitHub
        run: |
          git config --global user.email "${{secrets.GIT_USER_EMAIL}}"
          git config --global user.name "${{secrets.GIT_USER_NAME}}"
      
      - name: Install npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GIT }}
        run: npm ci

      - name: Cache Git Config
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.gitconfig
            ./package-lock.json
            ./node_modules/
          key: git-npm
      
  snyk:
    name: 'snyk'
    runs-on: ubuntu-latest
    needs: config
    permissions:
      security-events: write
      pull-requests: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Git Config
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.gitconfig
            ./package-lock.json
            ./node_modules/
          key: git-npm

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          category: my-analysis-tool
      
  owasp_depcheck:
    name: 'owasp_depcheck'
    runs-on: ubuntu-latest
    needs: config
    permissions:
      security-events: write
      pull-requests: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Cache Git Config
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.gitconfig
            ./package-lock.json
            ./node_modules/
          key: git-npm

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'tcc-bank-api'
          path: './'
          format: 'ALL'
          out: 'depcheck'
          args: >
            --enableRetired
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
      
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: depcheck/dependency-check-report.sarif

      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
            name: Depcheck report
            path:  ${{github.workspace}}/depcheck
